"""skill_optimizer species — Darwin-MCP Policy Species for Self-Refactoring.

The Brain's "clean-up crew": scans the live registry for skill pairs that
overlap semantically (same domain, similar names, near-identical purpose)
and either reports the candidates or generates a mutation payload that
would merge them into a single superior skill.

Strategies
----------
detect   Return a report of overlapping skill pairs — no mutations.
merge    Given two explicit skill names, generate a /evolve payload that
         merges their logic and retires the weaker one.
auto     Detect top-1 overlap pair and immediately enqueue a "optimize"
         backlog task so the Heartbeat handles the merge asynchronously.

Output schema (all strategies)
-------------------------------
{
  "status":    "ok" | "error",
  "strategy":  str,
  "pairs":     [ { "skill_a": str, "skill_b": str, "score": float,
                   "reason": str } ],
  "merge_payload": dict | null,   # populated for "merge" / "auto"
  "summary":   str
}
"""
from __future__ import annotations

import json
import logging
import re
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

_REGISTRY_PATH = (
    Path(__file__).resolve().parent.parent / "dna" / "registry.json"
)

# ---------------------------------------------------------------------------
# Similarity helpers
# ---------------------------------------------------------------------------

_STOPWORDS = frozenset(
    "the a an and or of in on to for with at by from is are was "
    "be been being do does did has have had will would can could "
    "should shall may might must species tool darwin mcp skill".split()
)


def _tokenise(text: str) -> set[str]:
    """Lower-case word tokens, strip stopwords."""
    words = re.findall(r"[a-z]+", text.lower())
    return {w for w in words if w not in _STOPWORDS and len(w) > 2}


def _jaccard(a: set[str], b: set[str]) -> float:
    """Jaccard similarity ∈ [0, 1]."""
    if not a and not b:
        return 0.0
    return len(a & b) / len(a | b)


def _skill_tokens(entry: dict, name: str) -> set[str]:
    """Combine name + short_description + description for comparison."""
    parts = [
        name,
        entry.get("short_description", ""),
        entry.get("description", ""),
        entry.get("entry_point", ""),
    ]
    return _tokenise(" ".join(p for p in parts if p))


OVERLAP_THRESHOLD = 0.30   # Jaccard ≥ this → candidate pair

# ---------------------------------------------------------------------------
# Core detection
# ---------------------------------------------------------------------------

def _load_registry(registry_path=None) -> dict:
    path = Path(registry_path) if registry_path else _REGISTRY_PATH
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8")).get("skills", {})
    except Exception as exc:
        logger.warning("skill_optimizer: cannot read registry: %s", exc)
        return {}


def _detect_pairs(skills: dict, threshold: float = OVERLAP_THRESHOLD) -> list[dict]:
    """Return all pairs whose Jaccard similarity ≥ threshold, sorted descending."""
    names = [n for n, e in skills.items() if e.get("status") == "active"]
    token_map = {n: _skill_tokens(skills[n], n) for n in names}
    pairs: list[dict] = []

    for i, a in enumerate(names):
        for b in names[i + 1:]:
            score = _jaccard(token_map[a], token_map[b])
            if score >= threshold:
                # Build a human-readable reason
                shared = token_map[a] & token_map[b]
                reason = f"shared tokens: {', '.join(sorted(shared)[:8])}"
                pairs.append({
                    "skill_a": a,
                    "skill_b": b,
                    "score": round(score, 3),
                    "reason": reason,
                })

    pairs.sort(key=lambda p: p["score"], reverse=True)
    return pairs


# ---------------------------------------------------------------------------
# Merge payload generator
# ---------------------------------------------------------------------------

def _merge_payload(skill_a: str, skill_b: str, skills: dict) -> dict:
    """Generate a request_evolution payload that merges two skills.

    The merged skill's code is a thin router that calls the richer of the
    two originals; the Mutator will test and promote it.

    The merged name follows the convention:  shorter_name + "_unified"
    unless one clearly subsumes the other (longer jaccard).
    """
    merged_name = _merged_name(skill_a, skill_b)

    desc_a = skills.get(skill_a, {}).get("short_description", skill_a)
    desc_b = skills.get(skill_b, {}).get("short_description", skill_b)

    code = f'''\
"""Merged skill: {merged_name}
Combines: {skill_a} + {skill_b}
Auto-generated by skill_optimizer — review before promoting.
"""
from __future__ import annotations


def {merged_name}(action: str = "", **kwargs) -> dict:
    """Unified entry point for {skill_a} and {skill_b}.

    Args:
        action: "{skill_a}" or "{skill_b}" to route explicitly,
                or omit to use the default ({skill_a}).
        **kwargs: Forwarded to the chosen underlying skill.
    """
    if action == "{skill_b}":
        from memory.species.{skill_b} import {skill_b}
        return {skill_b}(**kwargs)
    # Default path
    from memory.species.{skill_a} import {skill_a}
    return {skill_a}(**kwargs)
'''

    tests = f'''\
from memory.species.{merged_name} import {merged_name}


def test_{merged_name}_default_route():
    # Smoke-test: ensure the function is importable and callable.
    result = {merged_name}()
    assert isinstance(result, dict)


def test_{merged_name}_alternate_route():
    result = {merged_name}(action="{skill_b}")
    assert isinstance(result, dict)
'''

    return {
        "name": merged_name,
        "code": code,
        "tests": tests,
        "requirements": [],
        "description": f"Merged: {desc_a} + {desc_b}",
        "git_commit": False,
    }


def _merged_name(a: str, b: str) -> str:
    """Produce a stable merged skill name."""
    shorter, longer = (a, b) if len(a) <= len(b) else (b, a)
    # Strip trailing version/handler suffixes for cleaner names
    base = re.sub(r"(_handler|_classifier|_router|_agent|_tool)$", "", shorter)
    return f"{base}_unified"


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

def skill_optimizer(
    strategy: str = "detect",
    target_skills: Optional[list[str]] = None,
    registry_path: Optional[str] = None,
    threshold: float = OVERLAP_THRESHOLD,
) -> dict:
    """Analyse the registry for semantic skill overlap and act on findings.

    Args:
        strategy:      "detect" | "merge" | "auto"
        target_skills: [skill_a, skill_b] — required for "merge" strategy.
        registry_path: Override path to registry.json.
        threshold:     Jaccard similarity floor (default 0.30).

    Returns:
        Result dict (see module docstring for schema).
    """
    if strategy not in ("detect", "merge", "auto"):
        return {"status": "error", "error": f"Unknown strategy '{strategy}'"}

    # Validate merge args early — before registry I/O
    if strategy == "merge":
        if not target_skills or len(target_skills) < 2:
            return {
                "status": "error",
                "error": "strategy='merge' requires target_skills=[skill_a, skill_b]",
            }

    skills = _load_registry(registry_path)
    if not skills:
        return {
            "status": "ok",
            "strategy": strategy,
            "pairs": [],
            "merge_payload": None,
            "summary": "Registry is empty or unreadable.",
        }

    # ── detect ──────────────────────────────────────────────────────────────
    if strategy == "detect":
        pairs = _detect_pairs(skills, threshold=threshold)
        summary = (
            f"Found {len(pairs)} overlapping pair(s) among "
            f"{len(skills)} active skills "
            f"(Jaccard ≥ {threshold})."
        ) if pairs else (
            f"No semantic overlap found among {len(skills)} active skills "
            f"(threshold={threshold})."
        )
        return {
            "status": "ok",
            "strategy": strategy,
            "pairs": pairs,
            "merge_payload": None,
            "summary": summary,
        }

    # ── merge ────────────────────────────────────────────────────────────────
    if strategy == "merge":
        # target_skills already validated above
        skill_a, skill_b = target_skills[0], target_skills[1]
        for s in (skill_a, skill_b):
            if s not in skills:
                return {"status": "error", "error": f"Skill '{s}' not found in registry"}
        payload = _merge_payload(skill_a, skill_b, skills)
        return {
            "status": "ok",
            "strategy": strategy,
            "pairs": [{"skill_a": skill_a, "skill_b": skill_b, "score": 1.0, "reason": "explicit merge request"}],
            "merge_payload": payload,
            "summary": f"Merge payload generated for '{payload['name']}'. Submit to /evolve to promote.",
        }

    # ── auto ─────────────────────────────────────────────────────────────────
    if strategy == "auto":
        pairs = _detect_pairs(skills, threshold=threshold)
        if not pairs:
            return {
                "status": "ok",
                "strategy": strategy,
                "pairs": [],
                "merge_payload": None,
                "summary": "No overlapping pairs found — nothing to auto-merge.",
            }
        top = pairs[0]
        payload = _merge_payload(top["skill_a"], top["skill_b"], skills)

        # Enqueue an "optimize" task so the Heartbeat handles the actual merge
        try:
            from brain.engine.backlog import enqueue
            task_id = enqueue(
                task_type="evolve",
                payload=payload,
                priority=4,   # low priority — cosmetic cleanup, not critical
            )
            enqueue_msg = f"Enqueued 'evolve' backlog task {task_id} for '{payload['name']}'."
        except Exception as exc:
            enqueue_msg = f"Could not enqueue (backlog unavailable): {exc}"
            logger.warning(enqueue_msg)

        return {
            "status": "ok",
            "strategy": strategy,
            "pairs": pairs[:5],   # return top-5 for visibility
            "merge_payload": payload,
            "summary": (
                f"Top pair: {top['skill_a']} ↔ {top['skill_b']} "
                f"(score={top['score']}). {enqueue_msg}"
            ),
        }

    # Should never reach here
    return {"status": "error", "error": "Unreachable"}
